"""Post-deploy env file and completion banner."""
from __future__ import annotations

from pathlib import Path


class SummaryMixin:
    """Persist credentials/URLs for shells and render the final banner."""

    def _write_env_file(self) -> None:
        """Write /etc/profile.d/rodeo.sh so passwords and URLs are available as env vars.

        Loaded by every login shell on the Instruqt host — students can use
        $HARVESTER_ADMIN_PASSWORD, $RANCHER_ADMIN_PASSWORD, etc. in challenge scripts
        without having to parse the secrets file.
        """
        lines = ["# Rodeo lab credentials — generated by rodeo-cli, do not edit by hand"]
        if self.vip:
            lines += [
                f'export HARVESTER_VIP="{self.vip}"',
                f'export HARVESTER_URL="https://{self.vip}"',
                f'export HARVESTER_ADMIN_PASSWORD="{self.harvester_password}"',
            ]
        lines += [
            f'export RANCHER_URL="{self.rancher_api}"',
            f'export RANCHER_ADMIN_PASSWORD="{self.rancher_password}"',
        ]
        content = "\n".join(lines) + "\n"
        try:
            Path("/etc/profile.d/rodeo.sh").write_text(content)
        except Exception:
            # Non-root or read-only fs — write to ~/.rodeo/ as fallback
            from ...paths import rodeo_dir

            fallback = rodeo_dir() / "rodeo.env"
            try:
                fallback.write_text(content)
            except Exception:
                pass

    def _completion_summary(self) -> str:
        lines = [
            "\n",
            "  ┌─ Lab ready ──────────────────────────────────────────────┐\n",
            f"  │  Rancher URL    {self.rancher_api:<42}│\n",
        ]
        if self.vip:
            lines += [
                f"  │  Harvester URL  https://{self.vip:<38}│\n",
            ]
        lines += [
            "  │                                                          │\n",
            "  │  Username       admin                                    │\n",
        ]
        if self.vip:
            lines.append(f"  │  Harvester pw   {self.harvester_password:<42}│\n")
        lines += [
            f"  │  Rancher pw     {self.rancher_password:<42}│\n",
            "  │                                                          │\n",
            "  │  Passwords also in ~/.rodeo/secrets.yaml                 │\n",
            "  │  and $RANCHER_ADMIN_PASSWORD / $RANCHER_URL              │\n",
        ]
        if not self.vip:
            lines.append(
                "  │  Edge nodes: attach Elemental ISO + start VMs           │\n"
            )
        lines.append("  └──────────────────────────────────────────────────────────┘")
        return "".join(lines)
