"""rodeo init — scaffold a rodeo-plan.yaml and ~/.rodeo/secrets.yaml."""
from __future__ import annotations

import os
import secrets
import shutil
import stat
import string
from pathlib import Path

import click
from rich.console import Console

console = Console()

_TEMPLATES = Path(__file__).parent.parent / "data" / "templates"


def _random_password(length: int = 16) -> str:
    """Random password that satisfies Rancher complexity (letters+digits, 12+ chars)."""
    alphabet = string.ascii_letters + string.digits
    while True:
        pw = "".join(secrets.choice(alphabet) for _ in range(length))
        if any(c.isdigit() for c in pw) and any(c.isupper() for c in pw) \
                and any(c.islower() for c in pw):
            return pw


def _pick_password(ask: bool) -> tuple[str, str]:
    """Return (password, source). Precedence: --ask > $RODEO_PASSWORD > random.

    Never accept the password as a CLI argument — it would land in shell
    history and process listings.
    """
    if ask:
        pw = click.prompt(
            "Lab password (12+ chars, Rancher requires it)",
            hide_input=True, confirmation_prompt=True,
        )
        if len(pw) < 12:
            console.print("[red]✗  Password must be at least 12 characters (Rancher minimum).[/red]")
            raise SystemExit(1)
        return pw, "from prompt"

    env_pw = os.environ.get("RODEO_PASSWORD", "")
    if env_pw:
        if len(env_pw) < 12:
            console.print("[red]✗  $RODEO_PASSWORD must be at least 12 characters.[/red]")
            raise SystemExit(1)
        return env_pw, "from $RODEO_PASSWORD"

    return _random_password(), "random"


@click.command("init")
@click.option("--force", is_flag=True, help="Overwrite existing files.")
@click.option("--ask", "ask_password", is_flag=True,
              help="Prompt for the lab password instead of generating one.")
@click.argument("target_dir", default=".", type=click.Path())
def init_cmd(force: bool, ask_password: bool, target_dir: str) -> None:
    """Generate rodeo-plan.yaml and ~/.rodeo/secrets.yaml.

    \b
    Password source (first match wins):
      1. --ask            interactive hidden prompt
      2. $RODEO_PASSWORD  environment variable (CI / Instruqt setup scripts)
      3. generated        random 16 characters
    """
    dest = Path(target_dir).resolve()
    dest.mkdir(parents=True, exist_ok=True)
    plan_dest = dest / "rodeo-plan.yaml"
    secrets_dest = Path.home() / ".rodeo" / "secrets.yaml"

    if plan_dest.exists() and not force:
        console.print(f"[yellow]{plan_dest} already exists — use --force to overwrite.[/yellow]")
    else:
        shutil.copy(_TEMPLATES / "rodeo-plan.yaml", plan_dest)
        console.print(f"[green]✓[/green]  {plan_dest}")

    secrets_dest.parent.mkdir(parents=True, exist_ok=True)
    if secrets_dest.exists() and not force:
        console.print(f"[yellow]{secrets_dest} already exists — use --force to overwrite.[/yellow]")
    else:
        password, source = _pick_password(ask_password)
        secrets_dest.write_text(
            "# ~/.rodeo/secrets.yaml — kept out of version control\n"
            "# Generated by rodeo init. One lab-wide password for OS consoles,\n"
            "# Harvester dashboard, and Rancher admin.\n"
            f'harvester_os_password: "{password}"\n'
            f'lab_admin_password: "{password}"\n'
        )
        secrets_dest.chmod(stat.S_IRUSR | stat.S_IWUSR)  # chmod 600
        console.print(
            f"[green]✓[/green]  {secrets_dest}  [dim](chmod 600, password: {source})[/dim]"
        )

    console.print(
        "\nEdit [bold]rodeo-plan.yaml[/bold] for your environment, "
        "then set passwords in [bold]~/.rodeo/secrets.yaml[/bold]."
    )
    console.print("Run [bold]rodeo deploy[/bold] when ready.")
